name: Prebuilds

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'package.json'

jobs:
  build-prebuilds:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            os: linux
            arch: x64
          - runner: ubuntu-22.04-arm64
            os: linux
            arch: arm64
          - runner: macos-13
            os: darwin
            arch: x64
          - runner: macos-latest
            os: darwin
            arch: arm64
          - runner: windows-latest
            os: win32
            arch: x64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config

      - name: Install dependencies
        run: npm ci

      - name: Build native (release)
        run: npm run build:native:release

      - name: Make prebuild
        shell: bash
        run: |
          PREBUILD_PLATFORM=${{ matrix.os }} PREBUILD_ARCH=${{ matrix.arch }} node scripts/make-prebuild.js

      - name: Upload prebuilds artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.runner }}-${{ matrix.arch }}
          path: prebuilds/
